# permissions to do viewer fargatetasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fargatetask-viewer-role
rules:
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks/status
  verbs:
  - get
