# permissions to do edit fargatetasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fargatetask-editor-role
rules:
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks/status
  verbs:
  - get
  - patch
  - update
