
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-operator.hiraken.cf
  resources:
  - fargatetasks/status
  verbs:
  - get
  - patch
  - update
